-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.customer
(
    id integer NOT NULL DEFAULT nextval('customer_id_seq'::regclass),
    firstname character varying(20) COLLATE pg_catalog."default" NOT NULL,
    lastname character varying(20) COLLATE pg_catalog."default" NOT NULL,
    servedby integer,
    hasvhs integer,
    CONSTRAINT customer_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.employe
(
    id integer NOT NULL DEFAULT nextval('employe_id_seq'::regclass),
    salary integer,
    firstname character varying(20) COLLATE pg_catalog."default" NOT NULL,
    lastname character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT employe_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.salesteam
(
    id integer NOT NULL DEFAULT nextval('salesteam_id_seq'::regclass),
    employeid integer,
    salary integer,
    CONSTRAINT salesteam_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vhs
(
    id integer NOT NULL DEFAULT nextval('vhs_id_seq'::regclass),
    nameoftape character varying(60) COLLATE pg_catalog."default" NOT NULL,
    curentovner integer,
    deadline date NOT NULL,
    warehousid integer,
    CONSTRAINT vhs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.warehouse
(
    id integer NOT NULL DEFAULT nextval('warehouse_id_seq'::regclass),
    sumoftapes integer,
    CONSTRAINT warehouse_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customer_vhs
(
    customer_hasvhs integer,
    vhs_id integer NOT NULL DEFAULT nextval('vhs_id_seq'::regclass),
    dateofupdate date
);

CREATE TABLE IF NOT EXISTS public.employe_customer
(
    employe_id integer NOT NULL DEFAULT nextval('employe_id_seq'::regclass),
    customer_servedby integer,
    timeofupdate date
);

ALTER TABLE IF EXISTS public.salesteam
    ADD FOREIGN KEY (employeid)
    REFERENCES public.employe (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.warehouse
    ADD FOREIGN KEY (id)
    REFERENCES public.vhs (warehousid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.customer_vhs
    ADD FOREIGN KEY (customer_hasvhs)
    REFERENCES public.customer (hasvhs) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.customer_vhs
    ADD FOREIGN KEY (vhs_id)
    REFERENCES public.vhs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employe_customer
    ADD FOREIGN KEY (employe_id)
    REFERENCES public.employe (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employe_customer
    ADD FOREIGN KEY (customer_servedby)
    REFERENCES public.customer (servedby) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;